DELIMITER ;


CREATE TABLE IF NOT EXISTS `ds_access` (
  `role` varchar(100) NOT NULL DEFAULT '',
  `table_name` varchar(128) NOT NULL,
  `read` tinyint(4) DEFAULT 0,
  `write` tinyint(4) DEFAULT 0,
  `delete` tinyint(4) DEFAULT 0,
  `append` tinyint(4) DEFAULT 0,
  `existsreal` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`role`,`table_name`),
  KEY `fk_ds_access_ds` (`table_name`),
  CONSTRAINT `fk_ds_access_ds` FOREIGN KEY (`table_name`) REFERENCES `ds` (`table_name`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT  IGNORE INTO `ds_access` VALUES
('administration','blg_config',1,1,0,1,1),
('administration','crontab',0,1,1,1,1),
('administration','crontab_applications',0,0,0,0,1),
('administration','crontab_weekdays',0,0,0,0,1),
('administration','cron_queries',1,1,1,1,1),
('administration','dateien',0,1,1,1,0),
('administration','ds',1,1,0,0,1),
('administration','ds_access',1,1,0,0,1),
('administration','ds_addcommands',0,1,1,1,0),
('administration','ds_addcommands_xtypes',0,1,1,1,0),
('administration','ds_addcommand_locations',0,1,1,1,0),
('administration','ds_additional_columns',1,1,1,1,1),
('administration','ds_blg_column',1,1,0,0,0),
('administration','ds_class',1,1,1,1,1),
('administration','ds_column',1,1,0,0,1),
('administration','ds_column_form_label',1,1,0,0,1),
('administration','ds_column_form_properties',1,1,1,1,0),
('administration','ds_column_list_export',1,1,0,0,1),
('administration','ds_column_list_label',1,1,0,0,1),
('administration','ds_column_tagfields',1,1,1,1,1),
('administration','ds_column_types',1,1,1,1,0),
('administration','ds_combined_tables',1,1,1,1,0),
('administration','ds_contextmenu',1,1,1,1,1),
('administration','ds_contextmenu_groups',1,1,1,1,1),
('administration','ds_contextmenu_params',1,1,1,1,1),
('administration','ds_contextmenu_session_groups',1,0,0,0,1),
('administration','ds_dropdownfields',1,1,1,1,1),
('administration','ds_export_file_transfer',1,1,1,1,0),
('administration','ds_form_properties',1,1,1,1,0),
('administration','ds_import_file_transfer',1,1,1,1,0),
('administration','ds_nm_tables',1,1,0,0,1),
('administration','ds_preview_form_label',1,1,0,0,1),
('administration','ds_pug_templates',1,1,1,1,0),
('administration','ds_referenced_manual',0,1,1,1,0),
('administration','ds_referenced_manual_columns',0,1,1,1,0),
('administration','ds_reference_tables',1,1,0,0,1),
('administration','ds_renderer',1,1,1,1,0),
('administration','ds_renderer_stylesheet',1,1,1,1,0),
('administration','ds_renderer_stylesheet_attributes',1,1,1,1,0),
('administration','ds_renderer_stylesheet_groups',1,1,1,1,0),
('administration','ds_renderer_stylesheet_groups_assign',1,1,1,1,0),
('administration','ds_searchfields',1,1,1,1,0),
('administration','ds_send_mail',1,1,1,1,0),
('administration','ds_send_mail_to',1,1,1,1,0),
('administration','ds_statistics',1,0,0,0,0),
('administration','ds_sync_data',1,1,1,1,1),
('administration','ds_trigger',1,1,1,1,1),
('administration','ds_used_tables',1,1,1,1,0),
('administration','farben',0,1,1,1,0),
('administration','lager',0,1,1,1,1),
('administration','preisorientierung',0,1,1,1,1),
('_default_','crontab',1,0,0,0,1),
('_default_','crontab_applications',1,0,0,0,1),
('_default_','crontab_weekdays',1,0,0,0,1),
('_default_','cron_queries',0,0,0,0,1),
('_default_','dateien',1,0,0,0,0),
('_default_','ds',1,0,0,0,1),
('_default_','ds_addcommands',1,0,0,0,0),
('_default_','ds_addcommands_xtypes',1,0,0,0,0),
('_default_','ds_addcommand_locations',1,0,0,0,0),
('_default_','ds_additional_columns',0,0,0,0,1),
('_default_','ds_column_form_label',0,0,0,0,1),
('_default_','ds_column_form_properties',1,0,0,0,0),
('_default_','ds_column_list_label',0,0,0,0,1),
('_default_','ds_referenced_manual',1,0,0,0,0),
('_default_','ds_referenced_manual_columns',1,0,0,0,0),
('_default_','ds_reference_tables',0,0,0,0,1),
('_default_','farben',1,0,0,0,0),
('_default_','setup_parameters',1,0,0,0,0),
('_default_','view_ds_listfilters',1,0,0,0,0),
('_default_','view_session_groups',1,0,0,0,0);